# Generated by Django 4.1.2 on 2023-01-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_alter_app_user_image'),
        ('Matches', '0002_match_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='motm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motm', to='Users.player'),
        ),
    ]
