# Generated by Django 4.1.7 on 2023-03-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='images/teams/Logo_PiS_Jasne.png', upload_to='images/teams'),
        ),
    ]
