# Generated by Django 4.1.2 on 2022-11-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_player_position_alter_player_shirt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='mod',
            field=models.BooleanField(default=False),
        ),
    ]
