# Generated by Django 4.1.2 on 2022-11-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_referee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app_user',
            old_name='surname',
            new_name='last_name',
        ),
    ]
