# Generated by Django 4.1.2 on 2022-11-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_rename_surname_app_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='image',
            field=models.ImageField(default='images/users/default_profile.png', upload_to='images/users'),
        ),
    ]
