# Generated by Django 4.1.7 on 2023-03-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_alter_app_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='email',
            field=models.EmailField(default='samplemail@gmail.com', max_length=100),
        ),
    ]
