# Generated by Django 4.1.7 on 2023-03-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_app_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='email',
            field=models.EmailField(default='samplemail@gmail.com', max_length=100, unique=True),
        ),
    ]
