# Generated by Django 4.1.2 on 2022-11-30 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0001_initial'),
        ('Teams', '0001_initial'),
        ('Messages', '0005_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Messages.message')),
                ('date', models.DateField()),
                ('challenged_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenged_team', to='Teams.team')),
                ('challenging_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenging_team', to='Teams.team')),
                ('stadium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Matches.stadium')),
            ],
            bases=('Messages.message',),
        ),
    ]
