# Generated by Django 4.1.2 on 2022-10-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
